### ISSUE TITLE
Importing test cases from CSV giving SSL error

### ISSUE THREAD

**Issue by eliyahasan** [kiwitcms/Kiwi#1104]
I've written down a python utility for importing cases from a CSV fil to Kiwi. 
My Kiwi is setup as a docker container on an AWS instance. 

This is the error im getting while running the import utils,

(kiwi) [eabid@ip PythonScript]$ python main.py
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    class Main():
  File "main.py", line 12, in Main
    rpc_client = TCMS()
  File "/home/eabid/virtualenvs/kiwi/lib/python3.6/site-packages/tcms_api/__init__.py", line 96, in __init__
    config['tcms']['url']).server
  File "/home/eabid/virtualenvs/kiwi/lib/python3.6/site-packages/tcms_api/xmlrpc.py", line 111, in __init__
    self.server.Auth.login(username, password)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xmlrpc/client.py", line 1279, in send_request
    self.send_content(connection, request_body)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xmlrpc/client.py", line 1309, in send_content
    connection.endheaders(request_body)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

Link to my python import util: https://github.com/eliyahasan/kiwi-tcms-import-util

**Comment by atodorov** [comment]
A few things here:

1) Send your support requests to StackOverflow so that other people can see them more easily and help on a timely manner

2) Please consider adding your script to https://github.com/kiwitcms/api-scripts by sending a pull request

3) Looks like an issue with your Python libraries failing to validate the SSL certificate. To make matters worse you can't disable SSL validation for the Python version in RHEL, see
https://bugzilla.redhat.com/show_bug.cgi?id=1643454
