### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by OddanN** [kiwitcms/Kiwi#1962]
### Steps to Reproduce

Upgrade 8.1 -> 8.7
docker exec -it kiwi_web /Kiwi/manage.py showmigrations
Traceback (most recent call last):
  File "/Kiwi/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/venv/lib/python3.6/site-packages/tcms/settings/product.py", line 18, in <module>
    from .local_settings import *  # noqa: F401,F403
  File "/venv/lib/python3.6/site-packages/tcms/settings/local_settings.py", line 3, in <module>
    settings.MIDDLEWARE.remove('global_login_required.GlobalLoginRequiredMiddleware')
ValueError: list.remove(x): x not in list

**Comment by atodorov** [comment]
GlobalLoginRequired has been replaced, see changelog:
https://kiwitcms.readthedocs.io/en/latest/changelog.html#improvements

**Comment by OddanN** [comment]
> GlobalLoginRequired has been replaced, see changelog:
> https://kiwitcms.readthedocs.io/en/latest/changelog.html#improvements

And it's still a bug. Local_settings.py assumes that the global_login_required.GlobalLoginRequiredMiddleware parameter is definitely present, which is not true. It is necessary to check the existence of the parameter before deleting it.
Actually, I didn't have it. Thus, there are two options: 1.add a parameter so that it would be deleted during migration
2. remove settings.MIDDLEWARE.remove ('global_login_required.GlobalLoginRequiredMiddleware') from local_settings.py, because parameter does not exist and there is nothing to delete
