### ISSUE TITLE
./manage.py migrate gives "cannot CREATE INDEX "management_build" because it has pending trigger events"

### ISSUE THREAD

**Issue by andreydruz** [kiwitcms/Kiwi#2546]
### Description of problem
Trying to upgrade doker container from version 7 to last version on PostgreSQL
Done ./manage.py migrate
Get error:
cannot CREATE INDEX "management_build" because it has pending trigger events

### Version or commit hash (if applicable)

https://hub.docker.com/layers/kiwitcms/kiwi/latest/images/sha256-ab5e45e56af4dc5951b86597d533a12fd87e564e626af645091dc3b88eb99c55?context=explore

### Steps to Reproduce

1. install doker container version 7 with PostgreSQL 
2. Update doker container to last version
3. Do ./manage.py migrate

### Actual results

```
Operations to perform:
  Apply all migrations: admin, attachments, auth, contenttypes, core, django_comments, guardian, kiwi_auth, linkreference, management, sessions, sites, testcases, testplans, testruns
Running migrations:
  Applying management.0009_build_to_version...Traceback (most recent call last):
  File "/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.ObjectInUse: cannot CREATE INDEX "management_build" because it has pending trigger events

The above exception was the direct cause of the following exception:


Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/venv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/venv/lib64/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/venv/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/venv/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/venv/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/venv/lib64/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/venv/lib64/python3.8/site-packages/django/db/migrations/operations/fields.py", line 244, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/venv/lib64/python3.8/site-packages/django/db/backends/base/schema.py", line 608, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/venv/lib64/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 196, in _alter_field
    super()._alter_field(
  File "/venv/lib64/python3.8/site-packages/django/db/backends/base/schema.py", line 811, in _alter_field
    self.execute(self._create_index_sql(model, fields=[new_field]))
  File "/venv/lib64/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/venv/lib64/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: cannot CREATE INDEX "management_build" because it has pending trigger events
```

### Expected results

Upgrade

### Additional info (Python traceback, logs, etc.)

Probable you need to split migration, please read
https://stackoverflow.com/questions/12838111/django-db-migrations-cannot-alter-table-because-it-has-pending-trigger-events

**Comment by andreydruz** [comment]
Work around:
`/Kiwi/manage.py migrate management 0009_build_to_version --fake`
And make changes in db manualy

**Comment by atodorov** [comment]
> Trying to upgrade doker container from version 7 to last version on PostgreSQL

Do you mean upgrade Kiwi TCMS v7.0 to v10.3 ?

**Comment by andreydruz** [comment]
Yes

**Comment by atodorov** [comment]
The offending migration has been introduced into Kiwi TCMS v9.0, see
https://kiwitcms.readthedocs.io/en/latest/changelog.html#id54

Here's a similar message on the Postgres ML:
https://www.postgresql.org/message-id/B3E9F42B-4AD8-47EC-8E40-D96F2F906787%40medallia.com

It could be an issue with specific Postgres versions, not quite sure. Also not certain if this has been resolved in newer Postgres versions or not. We haven't seen this with our own deployments (Postgres 12) but OTOH we upgrade version to version b/c we're always running latest. 

There's a workaround describe in the Postgres ML thread, and also above.  

It could be that Postgres doesn't properly check the alter schema operations or could be that Django doesn't properly order these operations (we've seen migrations which can't be easily handled on other DB engines before) or it could be that the issue only happens with a specific version of Postgres, Kiwi TCMS and the actual information in the DB.  That's impossible to tell without in-depth debugging. 

However because version 9.0 has been released quite a long time ago there isn't much that can be done on our side either. We can't modify older migrations in newer versions b/c that would screw up existing deployments. Closing. Can't fix.
