### ISSUE TITLE
Upgrade to 4.1.3 fails

### ISSUE THREAD

**Issue by xbln** [kiwitcms/Kiwi#263]
### Description of problem
Upgrade of a perfectly working version 4.1.0 to 4.1.3 fails (kiwi_web stays in restarting loop) 

root@docker-1gb-fra1-01:~/kiwi# docker-compose up
Starting kiwi_db ...
Starting kiwi_db ... done
Starting kiwi_web ...
Starting kiwi_web
Attaching to kiwi_db, kiwi_web
db_1       | 180322 16:29:36 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
db_1       | 180322 16:29:36 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
web_1      | AH00526: Syntax error on line 34 of /etc/httpd/conf.d/kiwi-httpd.conf:
web_1      | SSLCertificateFile: file '/etc/kiwitcms/ssl/localhost.crt' does not exist or is empty
kiwi_web exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)

### Steps to Reproduce

1. Upgrade according to Upgrade Instructions:
cd Kiwi/
docker-compose down
docker pull kiwitcms/kiwi
docker pull centos/mariadb
docker-compose up -d

### Actual results
kiwi_web stays in restarting loop

**Comment by xbln** [comment]
No, I did not perform a Git Pull. Docker Images are usually self containing and need no action like Git pull. Anyhow, there was no instruction to do so in the installation manual. 
The former image did all that without trouble.
Compose file used is the standard file contained in Git without any modifications.

**Comment by atodorov** [comment]
post the contents of docker-compose.yml that reproduce the problem minus any passwords that you may have.

then try git pull and retry upgrading again, should fix the issue.

**Comment by xbln** [comment]
My docker-compose file is https://github.com/kiwitcms/Kiwi/blob/master/docker-compose.yml

I reeally dont want to install all the git stuff on my host. Why should I perform a git pull? I want a plain docker installation. What´s wrong with that?

**Comment by calvinmqc** [comment]
I tested the upgrade today, but it failed with the last step. It seems there were some changed to the package recently. The same test 2 weeks ago did work well. Any suggestion? Thanks!

cd Kiwi/
git pull                           >>I used "git clone https://github.com/kiwitcms/Kiwi.git" instead as I did not use git command before
docker-compose down
docker pull kiwitcms/kiwi 
docker-compose up -d       >> if I rum "docker ps -a", I can see the status as UP
docker exec -it kiwi_web /Kiwi/manage.py migrate  >>This step failed with error message as below:

[root@localhost Kiwi]# docker exec -it kiwi_web /Kiwi/manage.py migrate
Traceback (most recent call last):
  File "/Kiwi/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/venv/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 724, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/venv/lib/python3.5/site-packages/tcms/settings/product.py", line 1
    import os
    ^
IndentationError: unexpected indent

**Comment by atodorov** [comment]
> docker pull kiwitcms/kiwi

that is in fact 4.1.4 now


> File "/venv/lib/python3.5/site-packages/tcms/settings/product.py", line 1
import os
^
IndentationError: unexpected indent

there's no `import os` in our `product.py` if you have overriden this via `docker-compose.yml` or by other means just fix your config file.

**Comment by calvinmqc** [comment]
@atodorov You are right! This works if I remove the following entry. The reason I added it was just to enable email function.

             - ./product.py:/venv/lib64/python3.5/site-packages/tcms/settings/product.py:Z

Today I realize that I can enable email function by modify tcms/settings/common.py, and then add the following entry into the docker-compose.yml file. This way the revised version of common.py can be added into the container during setup. Although I am not very sure if I did this in the right way but the email function worked.

             - ./tcms/settings:/venv/lib64/python3.5/site-packages/tcms/settings:Z

Thanks a lot for checking my comment. Have a nice weekend!
