### ISSUE TITLE
V12.0 - Edit TC Causing for Error 500 - RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by NirBY** [kiwitcms/Kiwi#3084]
### Description of problem

Edit OLD TC, and save.

Error HTML - 
[RuntimeError at _case_176_edit_.txt](https://github.com/kiwitcms/Kiwi/files/10829902/RuntimeError.at._case_176_edit_.txt)
![image](https://user-images.githubusercontent.com/9214815/221325847-a1db73e4-2ee5-4565-9815-c8a3022345b3.png)

Log:
```
Internal Server Error: /case/176/edit/
Traceback (most recent call last):
  File "/venv/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/venv/lib64/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/venv/lib64/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/venv/lib64/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/venv/lib64/python3.9/site-packages/guardian/decorators.py", line 124, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/venv/lib64/python3.9/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/venv/lib64/python3.9/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/venv/lib64/python3.9/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/venv/lib64/python3.9/site-packages/tcms/testcases/views.py", line 179, in form_valid
    return super().form_valid(form)
  File "/venv/lib64/python3.9/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/venv/lib64/python3.9/site-packages/django/forms/models.py", line 548, in save
    self.instance.save()
  File "/venv/lib64/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/venv/lib64/python3.9/site-packages/django/db/models/base.py", line 878, in save_base
    post_save.send(
  File "/venv/lib64/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send

    return [
  File "/venv/lib64/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/venv/lib64/python3.9/site-packages/tcms/signals.py", line 101, in handle_emails_post_case_save
    email.email_case_update(instance)
  File "/venv/lib64/python3.9/site-packages/tcms/testcases/helpers/email.py", line 14, in email_case_update
    mailto(None, subject, recipients, body, cc=cc_list)
  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/venv/lib64/python3.9/site-packages/tcms/core/utils/mailto.py", line 47, in mailto
    email_thread.start()
  File "/usr/lib64/python3.9/threading.py", line 899, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

### Version or commit hash (if applicable)
V12.0

### Steps to Reproduce

1.Edit Old TC And Save

### Actual results
Getting RuntimeError

### Expected results
No error will show

### Additional info (Python traceback, logs, etc.)
1. It is not an Email issue verify with command (and got mail successfully):
```
docker exec -it kiwi_web /Kiwi/manage.py sendtestemail me@domain.com
```

2. Also not happens for New TC. Only Old ones.

**Comment by NirBY** [comment]
For Now Workaround it by disabling Mail notification on TC update/delete.

**Use this mount**:
```
- /containers/KiwiTCMS/Data/Config/email.py:/venv/lib64/python3.9/site-packages/tcms/testcases/helpers/email.py
```
**Updated File**:
[email.py](https://github.com/kiwitcms/Kiwi/files/10830508/email.txt)

**Comment by NirBY** [comment]
Upgrade Docker solved my issue. used ver (Docker version was 19.03.8 upgrade to 24.0.4)
