### ISSUE TITLE
[Kiwi 12.7] Sending test mail reports "certificate verify failed: unable to get local issuer certificate"

### ISSUE THREAD

**Issue by sansanpetrov** [kiwitcms/Kiwi#3464]
### Description of problem

I am using official docker Kiwi-CE. I changed common.py file as it's described in manual to to set e-mail notifications.
My SMTP-server requires SSL.
Debug from command line like
docker exec -it kiwi_web /Kiwi/manage.py sendtestemail user1@example1.ru
gives report:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

But all certificates are installed (I use defaults in container) and https is running correctly.

### Version or commit hash (if applicable)

Kiwi-CE (docker) v.12.7

### Steps to Reproduce

1. Change common.py file to set e-mail configuration. Enable SSL.
2. Run test e-mail via docker (as described in manual).

### Actual results
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

### Expected results
E-mail is received.

### Additional info (Python traceback, logs, etc.)
Traceback (most recent call last):
  File "/Kiwi/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/venv/lib64/python3.9/site-packages/django/core/management/commands/sendtestemail.py", line 35, in handle
    send_mail(
  File "/venv/lib64/python3.9/site-packages/django/core/mail/__init__.py", line 87, in send_mail
    return mail.send()
  File "/venv/lib64/python3.9/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/venv/lib64/python3.9/site-packages/django/core/mail/backends/smtp.py", line 127, in send_messages
    new_conn_created = self.open()
  File "/venv/lib64/python3.9/site-packages/django/core/mail/backends/smtp.py", line 85, in open
    self.connection = self.connection_class(
  File "/usr/lib64/python3.9/smtplib.py", line 1050, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/lib64/python3.9/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.9/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.9/smtplib.py", line 1057, in _get_socket
    new_socket = self.context.wrap_socket(new_socket,
  File "/usr/lib64/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib64/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/lib64/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

**Comment by atodorov** [comment]
It looks like the SSL certificate for the target SMTP server is invalid. Nothing Kiwi TCMS can do about that.
