### ISSUE TITLE
Test plan - Add attachment with non-english character -  UnicodeEncodeError: 'ascii' codec can't encode character '\\u010d'

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#350]
### Description of problem
Upload of attachment with non English character crashes app with error 500 -  UnicodeEncodeError: 'ascii' codec can't encode character '\\u010d' .

### Component (web, API, etc)
Web.

### Version or commit hash (if applicable)
4.1.4

### How often reproducible
Always

### Steps to Reproduce

1. Open test plan
2. Click on Attachments tab
3. Click on Add
4. Click on Browser and add attachment with non-English character e.g. (Gumb_povečaj.png)
5. Click on Add attachment

### Actual results
Error 500
`ERROR:django.request:Internal Server Error: /attachments/add-for/testplans/testplan/5/
Traceback (most recent call last):
File "/venv/lib64/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
response = get_response(request)
File "/venv/lib64/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/venv/lib64/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/venv/lib64/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
return func(request, *args, **kwargs)
File "/venv/lib64/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
return view_func(request, *args, **kwargs)
File "/venv/lib64/python3.5/site-packages/attachments/views.py", line 50, in add_attachment
form.save(request, obj)
File "/venv/lib64/python3.5/site-packages/attachments/forms.py", line 29, in save
super(AttachmentForm, self).save(*args, **kwargs)
File "/venv/lib64/python3.5/site-packages/django/forms/models.py", line 456, in save
self.instance.save()
File "/venv/lib64/python3.5/site-packages/django/db/models/base.py", line 729, in save
force_update=force_update, update_fields=update_fields)
File "/venv/lib64/python3.5/site-packages/django/db/models/base.py", line 759, in save_base
updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
File "/venv/lib64/python3.5/site-packages/django/db/models/base.py", line 842, in _save_table
result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
File "/venv/lib64/python3.5/site-packages/django/db/models/base.py", line 880, in _do_insert
using=using, raw=raw)
File "/venv/lib64/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/venv/lib64/python3.5/site-packages/django/db/models/query.py", line 1125, in _insert
return query.get_compiler(using=using).execute_sql(return_id)
File "/venv/lib64/python3.5/site-packages/django/db/models/sql/compiler.py", line 1283, in execute_sql
for sql, params in self.as_sql():
File "/venv/lib64/python3.5/site-packages/django/db/models/sql/compiler.py", line 1236, in as_sql
for obj in self.query.objs
File "/venv/lib64/python3.5/site-packages/django/db/models/sql/compiler.py", line 1236, in <listcomp>
for obj in self.query.objs
File "/venv/lib64/python3.5/site-packages/django/db/models/sql/compiler.py", line 1235, in <listcomp>
[self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
File "/venv/lib64/python3.5/site-packages/django/db/models/sql/compiler.py", line 1185, in pre_save_val
return field.pre_save(obj, add=True)
File "/venv/lib64/python3.5/site-packages/django/db/models/fields/files.py", line 287, in pre_save
file.save(file.name, file.file, save=False)
File "/venv/lib64/python3.5/site-packages/django/db/models/fields/files.py", line 87, in save
self.name = self.storage.save(name, content, max_length=self.field.max_length)
File "/venv/lib64/python3.5/site-packages/django/core/files/storage.py", line 48, in save
name = self.get_available_name(name, max_length=max_length)
File "/venv/lib64/python3.5/site-packages/django/core/files/storage.py", line 72, in get_available_name
while self.exists(name) or (max_length and len(name) > max_length):
File "/venv/lib64/python3.5/site-packages/django/core/files/storage.py", line 308, in exists
return os.path.exists(self.path(name))
File "/venv/lib64/python3.5/genericpath.py", line 19, in exists
os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\\u010d' in position 60: ordinal not in range(128)`

### Expected results
Application returns user-friendly error that filename has characters which are not allowed.

**Comment by atodorov** [comment]
@Prome88 can you give some details about the system you are seeing this error on? Especially if the localization environment is set to UTF8 or not. On Linux these are the LC_*/LANG env variables.

Also please attach a file with the offending name (can be empty) so we can try and reproduce.

**Comment by atodorov** [comment]
Upstream has gone silent on this bug and there isn't much I can do unless they can reproduce. Follow
https://github.com/bartTC/django-attachments/issues/49 for the updates. We can pick up new versions of django-attachments once they become available.
