### ISSUE TITLE
ImportError: No module named 'secrets'

### ISSUE THREAD

**Issue by sanjeev1990** [kiwitcms/Kiwi#351]
My All setup has been done. While I'm trying the **./manage.py migrate** command getting the following error.

```
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sanjeev/virtualenvs/kiwi/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/sanjeev/virtualenvs/kiwi/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/sanjeev/virtualenvs/kiwi/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/sanjeev/virtualenvs/kiwi/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/sanjeev/virtualenvs/kiwi/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/sanjeev/virtualenvs/kiwi/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/sanjeev/Documents/Kiwi/tcms/core/contrib/auth/models.py", line 4, in <module>
    import secrets
ImportError: No module named 'secrets'
```
I have checked for 'secrets' module and the requirement is satisfied. Please find the details below.

```
(kiwi) sanjeev@sanjeev-HP-Laptop-15-bs0xx:~/Documents/Kiwi$ pip3 install django-secrets
Requirement already satisfied: django-secrets in /home/sanjeev/virtualenvs/kiwi/lib/python3.5/site-packages (1.0.1)
Requirement already satisfied: Django>=1.5 in /home/sanjeev/virtualenvs/kiwi/lib/python3.5/site-packages (from django-secrets) (2.0.5)
Requirement already satisfied: future in /home/sanjeev/virtualenvs/kiwi/lib/python3.5/site-packages (from django-secrets) (0.16.0)
Requirement already satisfied: six in /home/sanjeev/virtualenvs/kiwi/lib/python3.5/site-packages (from django-secrets) (1.11.0)
Requirement already satisfied: pytz in /home/sanjeev/virtualenvs/kiwi/lib/python3.5/site-packages (from Django>=1.5->django-secrets) (2018.4)
```
Any help ?
Thanks in advance.

**Comment by atodorov** [comment]
Use Python 3.6. Older versions are not supported.

**Comment by vandelin586** [comment]
git bash throwing same error, no modules named secrets
$ python --version
Python 3.7.3
